import {
  ArrowLeftRight,
  Award,
  BadgeDollarSign,
  Banknote,
  Beer,
  Bike,
  Briefcase,
  CalendarClock,
  CalendarDays,
  Car,
  ChartNoAxesCombined,
  Church,
  CircleDollarSign,
  CircleEllipsis,
  CircleOff,
  Coins,
  CreditCard,
  FerrisWheel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  HeartPulse,
  House,
  Inbox,
  Landmark,
  Laptop,
  PawPrint,
  PencilRuler,
  PersonStanding,
  PiggyBank,
  Plane,
  PlugZap,
  ReceiptText,
  RotateCcw,
  Scale,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Sparkles,
  TicketPercent,
  Train,
  TrainFront,
  TrendingUp,
  UserRound,
  Utensils,
  WalletCards,
  Wifi,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  'arrow-left-right': ArrowLeftRight,
  award: Award,
  'badge-dollar-sign': BadgeDollarSign,
  banknote: Banknote,
  beer: Beer,
  bike: Bike,
  briefcase: Briefcase,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  car: Car,
  'chart-no-axes-combined': ChartNoAxesCombined,
  church: Church,
  'circle-dollar-sign': CircleDollarSign,
  'circle-ellipsis': CircleEllipsis,
  'circle-off': CircleOff,
  coins: Coins,
  'credit-card': CreditCard,
  'ferris-wheel': FerrisWheel,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  'heart-pulse': HeartPulse,
  house: House,
  inbox: Inbox,
  landmark: Landmark,
  laptop: Laptop,
  'paw-print': PawPrint,
  'pencil-ruler': PencilRuler,
  'person-standing': PersonStanding,
  'piggy-bank': PiggyBank,
  plane: Plane,
  'plug-zap': PlugZap,
  'receipt-text': ReceiptText,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  scissors: Scissors,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  sparkles: Sparkles,
  'ticket-percent': TicketPercent,
  train: Train,
  'train-front': TrainFront,
  'trending-up': TrendingUp,
  'user-round': UserRound,
  utensils: Utensils,
  'wallet-cards': WalletCards,
  wifi: Wifi,
}

export const selectableIcons = Object.keys(iconMap)

export function iconFor(key: string) {
  return iconMap[key] ?? CircleDollarSign
}
