import {
  Banknote,
  Bike,
  Briefcase,
  CalendarDays,
  Car,
  ChartNoAxesCombined,
  CircleDollarSign,
  Coins,
  CreditCard,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  PawPrint,
  Plane,
  ReceiptText,
  RotateCcw,
  Scale,
  Shirt,
  ShoppingBag,
  Sparkles,
  Train,
  UserRound,
  Utensils,
  WalletCards,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  banknote: Banknote,
  bike: Bike,
  briefcase: Briefcase,
  'calendar-days': CalendarDays,
  car: Car,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'circle-dollar-sign': CircleDollarSign,
  coins: Coins,
  'credit-card': CreditCard,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  'heart-pulse': HeartPulse,
  house: House,
  landmark: Landmark,
  'paw-print': PawPrint,
  plane: Plane,
  'receipt-text': ReceiptText,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  train: Train,
  'user-round': UserRound,
  utensils: Utensils,
  'wallet-cards': WalletCards,
}

export const selectableIcons = Object.keys(iconMap)

export function iconFor(key: string) {
  return iconMap[key] ?? CircleDollarSign
}
